#!/usr/bin/python
########
#
#  Script to help automate the download or chromecasting TV or movies from
#  Kodi's Exodus plugin
#
#  Run by `./stream download` or `./stream cast`
#
#  Requirements:
#    python
#    google chrome
#    subliminal                          at https://github.com/Diaoul/subliminal
#    stream2chromecast (aliased as cast) at https://github.com/Pat-Carter/stream2chromecast
#    ffmpeg
#
########


import os, re, sys, urllib

def stop_now(query="Stop now? [y/n]"):
    if len(sys.argv) == 1:
        return
    if raw_input(query) == 'y':
        sys.exit()


"Script starts here"

url_regex = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&~+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
streams   = os.popen("./skodus.sh openload.co").read()
urls      = re.findall(url_regex, streams)

for url in urls:
    filename = url.split("/")[-1]
    filetype = filename.split(".")[-1].lower()
    print "Trying %s" % (url)

    if "mkv.mp4" in filename.lower():
        continue
    elif filetype == 'mp4':
        print("Getting the URL of the mp4 from openload...")
        resp    = urllib.urlopen(url)
        outputs = os.popen("./openload.exp %s" % (url)).read()

        try:
            mp4_url = re.findall(url_regex, outputs)[1]
        except IndexError:
            print("Can't find URL here...")
            continue

        print("Found url:   %s" % (mp4_url))

        print("Downloading the subtitles in Spanish...")
        srt, subs = None, ""
        essub = os.popen("subliminal download -l es -e utf8 %s" % (filename)).read()

        if len(re.findall('Downloaded 0 subtitle',essub)) == 1:
            print("Downloading the subtitle in English instead...")
            ensub = os.popen("subliminal download -l en -e utf8 %s" % (filename)).read()

            if len(re.findall('Downloaded 1 subtitle',ensub)) == 1:
                print("Translating the English subs to Espanol...")
                doublesub = os.system("doublesub -T es -F en -t -f %s.en.srt" % (filename[:-4]))
                srt = "%s.en-es.srt" % (filename[:-4])
            else:
                print("Could not find the English subs too!")
        else:
            srt = "%s.es.srt" % (filename[:-4])


        if srt:
            print("Converting it to vtt...")
            os.system("srt2vtt %s" % (srt))
            subs_opts = "-subtitles %s.vtt " % srt[:-4]

        if sys.argv[1] == "download":
            print("Downloading the file...")
            os.system("curl -C - -L -o %s %s" % (filename, mp4_url))

            if srt:
                print("Adding subs into mp4 file")
                os.system("ffmpeg -i %s -i %s -c copy -c:s mov_text %s.mp4" % (filename, srt, srt[:-4]))
        elif sys.argv[1] == "cast":
            print("Casting it to Chromecast...")
            os.system("cast %s-playurl %s" % (subs, mp4_url))

        break
