#!/usr/bin/python
import os, re, sys, urllib

def stop_now(query="Stop now? [y/n]"):
    if len(sys.argv) == 1:
        return
    if raw_input(query) == 'y':
        sys.exit()

"Script starts here"

url_regex = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&~+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
streams   = os.popen("./skodus.sh openload.co").read()
urls      = re.findall(url_regex, streams)

for url in urls:
    filename = url.split("/")[-1]
    filetype = filename.split(".")[-1].lower()
    print "Trying %s" % (url)

    if "mkv.mp4" in filename.lower():
        continue
    elif filetype == 'mp4':
        "Gets the URL of the mp4 from openload"
        resp    = urllib.urlopen(url)
        outputs = os.popen("./openload.exp %s" % (url)).read()
        mp4_url = re.findall(url_regex, outputs)[1]
        print mp4_url
        stop_now()

        print("Downloading the subtitle in Spanish...")
        srt, subs = None, ""
        essub = os.popen("subliminal download -l es -e utf8 %s" % (filename)).read()
        stop_now()

        if len(re.findall('Downloaded 0 subtitle',essub)) == 1:
            print("Downloading the English subs...")
            ensub = os.popen("subliminal download -l en -e utf8 %s" % (filename)).read()
            stop_now()

            if len(re.findall('Downloaded 1 subtitle',ensub)) == 1:
                print("Translating the English subs to Espanol...")
                doublesub = os.system("doublesub -T es -F en -t -f %s.en.srt" % (filename[:-4]))
                srt = "%s.en-es.srt" % (filename[:-4])
                stop_now()

        else:
            srt = "%s.es.srt" % (filename[:-4])


        if srt:
            print("Converting it to vtt...")
            os.system("srt2vtt %s" % (srt))
            subs = "-subtitles %s.vtt " % srt[:-4]
            stop_now()


        print("Casting it to Chromecast...")
        os.system("cast %s-playurl %s" % (subs, mp4_url))
        break
