#!/usr/bin/python
import os, re, sys, urllib

def stop_now(query="Stop now? [y/n]"):
    if raw_input(query) == 'y':
        sys.exit()

"Script starts here"

url_regex = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&~+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
streams   = os.popen("./skodus.sh openload.co").read()
urls      = re.findall(url_regex, streams)

for url in urls:
    filename = url.split("/")[-1]
    filetype = filename.split(".")[-1].lower()
    print "Trying %s" % (url)

    if "mkv.mp4" in filename.lower():
        continue
    elif filetype == 'mp4':
        "Gets the URL of the mp4 from openload"
        resp    = urllib.urlopen(url)
        outputs = os.popen("./openload.exp %s" % (url)).read()
        mp4_url = re.findall(url_regex, outputs)[1]
        print mp4_url
        stop_now()

        "Downloads the subtitle in Spanish"
        os.system("subliminal download -l es -e utf8 %s" % (filename))
        stop_now()

        "Converts it to vtt"
        os.system("srt2vtt %ses.srt" % (filename[:-3]))
        stop_now()

        "Casting it to Chromecast"
        os.system("cast -subtitles %ses.vtt -playurl %s" % (filename[:-3], mp4_url))
        break
